version:  "3.7"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: wlpb 
    container_name: wlpbserver
    ports:
      - "9090:9090"
  
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: wlc
    container_name: wlclient
    # command: npx serve -l 9191
    ports:
      - "80:9191"
